config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'prototypes#index'
  resources :users, only: [:edit, :show, :update]
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
    resources :tags, only: [:index, :show]

  scope module: :prototypes do
    resources :popular, only: :index
    resources :new, only: :index
  end

end

app/controllers/prototypes/new_controller.rb
class Prototypes::NewController < ApplicationController

  def index
    @prototypes = Prototype.created_desc.page(params[:page]).per(8)
    render template: "prototypes/index"
  end

end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController

  def index
    @prototypes = Prototype.likes_desc.page(params[:page]).per(8)
    render template: "prototypes/index"
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_prototype, only: [:show, :destroy, :update,:edit]
  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    @prototypes = Prototype.all.page(params[:page]).per(8)
  end

  def new
    @prototype = Prototype.new
    @prototype.images.build
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)
    if @prototype.save
      redirect_to root_path, flash: { success: "Successfully uploaded your prototype!!" }
    else
      flash.now[:alert] = 'Posted prototype unsuccessfully'
      render :new
    end
  end

  def show
    @user = @prototype.user
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
    @tags = @prototype.tag_list

  end

  def destroy
    @prototype.destroy
    redirect_to root_path, flash: { success: "Deleted your prototype" }
  end

  def edit
  end

  def update
    if @prototype.update(prototype_params)
      redirect_to root_path, flash: { success: "Updated your prototype" }
    else
      flash.now[:alert] = 'Failed to Update Prototype'
      render :edit
    end
  end

  private

    def prototype_params
      params.require(:prototype).permit(
        :name,
        :catchcopy,
        :concept,
        images_attributes: [:id, :image_url, :status, :prototype_id]
        ).merge(tag_list: params[:prototype][:tag])
    end

    def set_prototype
      @prototype = Prototype.find(params[:id])
    end

    def correct_user
    user = Prototype.find(params[:id]).user
    if current_user != user
      redirect_to root_path
    end
  end


end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && prototype.user == current_user
    .dropdown.drop_menu_location
      %btn.btn.btn-default.dropdown-toggle{"aria-expanded": "false", "data-toggle": "dropdown", href: "#", type: "button",id: "dropdownMenu"}ACTION
      %ul.dropdown-menu{aria: {labelledby: "dropdownMenu1"}}
        %li
          = link_to "Delete", prototype_path(prototype), method: :delete, class: "dropdown"
        %li
          = link_to "Edit", edit_prototype_path(prototype), class: "dropdown"
  .thumbnail
    = link_to prototype_path(prototype) do
      = image_tag prototype.get_main_img
      .caption
        %h3
        = prototype.name
        .proto-meta
          .proto-user
            = link_to user_path(prototype.user) do
              = "by #{prototype.user.nickname}"
          .proto-posted
            = prototype.date
        %ul.proto-tag-list.list-inline
          - prototype.tag_list.each do |tag|
            %li
              = link_to "#{tag}", tag_path(tag), class: "btn btn-default"

app/views/prototypes/edit.html.haml
- if @prototype.errors.any?
  %ul
    - @prototype.errors.full_messages.each do |msg|
      %li= msg
.container.proto-new
  = form_for @prototype do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_field :name, value: @prototype.name
      .row
        .col-md-12
          .cover-image-upload.js-img-preview
            = f.fields_for :images, @prototype.images.main do |image_form|
              = image_form.file_field :image_url
              = image_form.hidden_field :status, value: "main"
        .col-md-12
          %ul.proto-sub-list.list-group
            - @prototype.images.sub.each do |sub|
              %li.list-group-item.col-md-4
                .image-upload.js-img-preview
                  = f.fields_for :images, sub do |image_form|
                    = image_form.file_field :image_url
                    = image_form.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          = f.text_field :catchcopy, placeholder: @prototype.catchcopy
        .col-md-12
          = f.text_area :concept, cols: "30", rows: "4", placeholder: @prototype.concept
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "UI"
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "Application"
      .row.text-center.proto-btn
        = f.submit 'Publish', class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", popular_index_path
        %li{role: "presentation"}
          = link_to "Newest PROTO", new_index_path
      %button.btn.btn-default.col-lg-1
        = link_to "View Tags", tags_path, type: "button"

.container.proto-list
  .row
    = render partial: "prototypes/prototype", collection: @prototypes
.text-center
  = paginate(@prototypes)

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    - if @prototype.errors.any?
      %ul
        - @prototype.errors.full_messages.each do |msg|
          %li= msg
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_field :name, placeholder: "Title"
      .row
        .col-md-12
          .cover-image-upload.js-img-preview
            = f.fields_for :images do |image_form|
              = image_form.file_field :image_url
              = image_form.hidden_field :status, value: "main"
        .col-md-12
          %ul.proto-sub-list.list-group
            - 3.times do
              %li.list-group-item.col-md-4
                .image-upload.js-img-preview
                  = f.fields_for :images do |image_form|
                    = image_form.file_field :image_url
                    = image_form.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          = f.text_field :catchcopy, placeholder: "Catch Copy"
        .col-md-12
          = f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "Web Design"
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "UI"
            .col-md-3
              = text_field_tag "prototype[tag][]", "", placeholder: "Application"
      .row.text-center.proto-btn
        = f.submit 'Publish', class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@user) do
            %img.media-object{alt: "user_avatar", src: @user.avatar, style: "width: 64px; height: 64px;"}
        .media-body
          %h4
          .top-aligned-media.media-heading
            = @prototype.name
          .proto-user
            = link_to user_path(@user) do
              = "by #{@user.nickname}"
            %span.degree
              = @user.group
              = @user.work
    .col-md-6.text-right#like-button
      = render partial: 'likes/like', locals: { prototype: @prototype}
  .row
    .col-md-9
      = image_tag @prototype.get_main_img, class: "img-responsive"
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.images.sub.each do |image|
          %li.list-group-item
            .img-responsive
              = image_tag image.image_url, class: "img-responsive"
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    = render partial: "tags/tag_list"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num#comments-count
        (#{@prototype.comments.count})
    #comment_area.col-md-8
      #comments
        = render @comments
    .col-md-8
      - if user_signed_in?
        = form_for [@prototype, @comment], remote: true do |f|
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :text, placeholder: "Your comments", rows: "3", class: "textarea form-control", id: "comment_field"
            .form-group.col-md-2
              = f.submit 'Comment', class: "button btn btn-primary"