config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'prototypes#index'
  resources :users, only: [:edit, :show, :update]
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
    resources :tags, only: [:index, :show]

  scope module: :prototypes do
    resources :popular, only: :index
    resources :new, only: :index
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :like_count
  belongs_to :user

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_prototypes

  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
  end

  private

  def set_prototypes
    @prototypes = Prototype.all
  end

end

app/views/likes/_like.html.haml
- if user_signed_in?
  - if prototype.like_user(current_user.id)
    %button.btn.btn-default
      = link_to prototype_like_path(prototype_id: prototype.id, id: prototype.user_id), method: :delete, id: "like-button", remote: true do
        = image_tag("icon_red_heart.svg")
      Like
      %span.num
      = prototype.like_count

  - else
    %button.btn.btn-default
      = link_to prototype_likes_path(prototype_id: prototype.id, id: prototype.user_id), id: "like-button", method: :post, remote: true do
        = image_tag("icon_heart.svg")
      Like
      %span.num
      = prototype.like_count

- else
  %button.btn.btn-default
    = link_to new_user_session_path do
      = image_tag("icon_heart.svg")
    Like
    %span.num
    = prototype.like_count

app/views/likes/create.js.erb
$("#like-button").html("<%= j (render partial: 'like', locals: { prototype: @prototype, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
$("#like-button").html("<%= j (render partial: 'like', locals: { prototype: @prototype,  likes: @likes, like: @like}) %>");